# crust:modes.toml
# This config contains options to control the 'modes' added by Crust. Some examples of Crust modes are magnet mode,
#   super speed mode, and undying mode.
# 
# This config is for server-side settings. Client preferences are requested by using /crustmode or Crust's extra
#   inventory buttons (client_extra_inv_buttons.toml).


# Category: general
# Options that apply to the 'modes' added by Crust, in general.


  # Subcategory: op_level
  # The op levels (aka permission levels) required to enable/disable Crust's various modes. You can disable any mode
  #   by setting this level very high (e.g., 5).
  # Vanilla op levels used are:
  #   0 - Chat/whispers, Access to limited info
  #   1 - Can bypass spawn protection
  #   2 - Can use cheats, Access to info that can be used to cheat
  #   3 - Can ban/whitelist players, 'Moderator'
  #   4 - All permissions, Server management
  #  * Requires a WORLD restart to take effect *

    # <Integer> Range: Any Value, Default: 0
    general.op_level.magnet = 0
    # <Integer> Range: Any Value, Default: 2
    general.op_level.undying = 2
    # <Integer> Range: Any Value, Default: 2
    general.op_level.unbreaking = 2
    # <Integer> Range: Any Value, Default: 2
    general.op_level.uneating = 2
    # <Integer> Range: Any Value, Default: 2
    general.op_level.super_vision = 2
    # <Integer> Range: Any Value, Default: 2
    general.op_level.super_speed = 2
    # <Integer> Range: Any Value, Default: 2
    general.op_level.destroy_on_pickup = 2

  # Subcategory: default
  # The default settings for Crust's various modes initially applied to players. Note that these mode settings will be
  #   applied regardless of op level; if the player does not have permission to enable/disable the mode, they will be
  #   'stuck' with whatever is assigned here.

    # The maximum range (blocks) for magnet mode. If 0, magnet mode will be off by default.
    # <Number> Range: ≥ 0.0, Default: 0.0
    general.default.magnet = 0.0
    # <Boolean> Valid Values: { true, false }, Default: false
    general.default.undying = false
    # <Boolean> Valid Values: { true, false }, Default: false
    general.default.unbreaking = false
    # When dropping below this food level (half-drumsticks), uneating mode restores hunger. If 0, uneating mode will
    #   be off by default.
    # <Integer> Range: 0 ~ 20, Default: 0
    general.default.uneating = 0
    # <Boolean> Valid Values: { true, false }, Default: false
    general.default.super_vision = false
    # The speed multiplier applied while sprinting. If 1, super speed mode will be off by default.
    # <Number> Range: ≥ 1.0, Default: 1.0
    general.default.super_speed = 1.0
    # <Boolean> Valid Values: { true, false }, Default: false
    general.default.destroy_on_pickup = false


# Category: magnet_mode
# Options that apply to Crust's magnet mode.

  # The highest maximum range (blocks) allowed for magnet mode. Max range is a client preference.
  # <Number> Range: ≥ 0.0, Default: 10.0
  magnet_mode.max_range_limit = 10.0
  # The maximum speed (blocks/sec) for items pulled by magnet mode. Speed is higher the closer the item is to the
  #   player, scaling down to 0 m/s at the player's max range.
  # <Number> Range: ≥ 0.0, Default: 10.0
  magnet_mode.max_speed = 10.0
  # The time delay (ticks) before freshly dropped items are pulled by magnet mode.
  # Setting this to a low value will cause items to fly around your face until their pickup delay expires. The default
  #   prevents face-flying for all vanilla drops, but many drops only have a pickup delay of 10.
  # <Integer> Range: ≥ 0, Default: 40
  magnet_mode.delay = 40


# Category: super_speed_mode
# Options that apply to Crust's super-speed mode.

  # The highest maximum speed multiplier allowed for super-speed mode. Actual speed is a client preference.
  # Warning: Very large speed multipliers might break the game's physics.
  # <Number> Range: ≥ 1.0, Default: 12.0
  super_speed_mode.speed_limit = 12.0
