
#General Settings
[General]
	#Ignore speed boosts for field of view
	useFOVFix = true
	#Use FOV Fix to normalize FOV changes
	useFOVNormalize = true
	#Default state of FOVfix on login (enabled = true, disabled = false)
	fovFixDefaultState = true
	#Use sounds
	useSounds = true

["Charging Base Energy Meter Settings"]
	#value to manually set the meter at.
	# Useful for trying different colors in real time
	#Range: 0.0 ~ 100.0
	chargingBaseEnergyMeterDebugValue = 0.0
	#charging base meter glass red color amount (0 - 100)
	#Range: 0 ~ 100
	chargingBaseEnergyMeterGlassRedPercent = 100
	#charging base meter glass blue color amount (0 - 100)
	#Range: 0 ~ 100
	chargingBaseEnergyMeterGlassBluePercent = 100
	#charging base meter glass green color amount (0 - 100)
	#Range: 0 ~ 100
	chargingBaseEnergyMeterGlassGreenPercent = 100
	#charging base meter glass alpha color amount (0 - 100)
	#Range: 0 ~ 100
	chargingBaseEnergyMeterGlassAlphaPercent = 85
	#charging base meter bar red color amount (0 - 100)
	#Range: 0 ~ 100
	chargingBaseEnergyMeterBarRedPercent = 0
	#charging base meter bar green color amount (0 - 100)
	#Range: 0 ~ 100
	chargingBaseEnergyMeterBarGreenPercent = 100
	#charging base meter bar blue color amount (0 - 100)
	#Range: 0 ~ 100
	chargingBaseEnergyMeterBarBluePercent = 0
	#charging base meter bar alpha color amount (0 - 100)
	#Range: 0 ~ 100
	chargingBaseEnergyMeterBarAlphaPercent = 85

["Development Settings"]
	#Enable debugging info
	enableDebugging = false

