
#EU P2P Tunnel Config
[EUP2PConfig]
	#Is the current evenly distributed based on the number of P2P output ports.
	#For Example:If the value is true, the system will only work properly if the input current can be evenly divided by the number of P2P output ports.
	#是否根据P2P输出端的数量均分电流
	#例如：如果该值为真，当输入电流大小可以整除P2P输出端口数量时系统才会正常工作
	needBalance = true

